# Assignment 1

## First Half

1.	Generate a tuple from the set ["aman", "222", 777, 400.4]
2.	Create a dictionary of your basic data : (a) Roll No (b) Last Name (c) First Name (d) Date of birth. Print out the values and keys.
3.	Use rand function to generate a 2-dimensional random array with seed.
4.	Generate a single random number in [0.0, 1.0]. Find the absolute value of (-1234)
5.	Return a random integer N such that 20 <= N <= 90. 
6.	Given a population or set[11, 12, 13,14, 15]
- Return a 3 length list of unique elements without replacement.
- Shuffle the above set
- Print a random number from the set
7.	Write the text "The King is Dead, Long Live The King" on to a file in your hard drive; read and print the text.
8.	Create an illustrative function to demonstrate use of: if, elif and else (b) for, while, break and continue. 
9.	Given a string "The King is Dead, Long Live The King" 
- Print the complete string
- Print first character of the string
- Print characters starting from 3rd to 5th
- Print string starting from 3rd character
- Split the words
10. An array can be created from a list:  Create an array from a list comprising of numbers 1,4,5,8 (treat them as floats).Slice the above array to display first and second elements

### Question 1

In [2]:
s = set(["aman", "222", 777, 400.4])
tup = tuple(s)
print(tup)
print(type(tup))

(400.4, 777, 'aman', '222')
<class 'tuple'>


### Question 2

In [3]:
dict = {'roll' : 20208,
        'name' : 'Aravind',
        'dob' : '08-05-02'}
print(dict)

{'roll': 20208, 'name': 'Aravind', 'dob': '08-05-02'}


### Question 3

In [4]:
import numpy as np

In [6]:
arr = np.random.randint(9,size=(2,4))
arr

array([[3, 6, 7, 0],
       [7, 7, 6, 6]])

### Question 4

In [14]:
import random

In [15]:
num = random.randint(1,10)
print(num)
print(abs(-1234))

1
1234


### Question 5

In [17]:
num = random.randint(20,90)
print(num)

82


### Question 6

In [6]:
import numpy as np
import random
li1=[11, 12, 13,14, 15]

newli1=random.sample(li1,3)
print(newlist1)

nparr=np.array(li1)
np.random.shuffle(nparr)

print(nparr)

newli1=random.sample(li1,1)
print(newli1)

[14]
[11 15 13 14 12]
[12]


### Question 7

In [57]:
file1 = open("q7.txt","a")
file1.write("The King is Dead, Long Live The King ")
file1.close()

file1 = open("q7.txt", "r+")
print('Read : ', file1.read())
file1.close()


Read :  The King is Dead, Long Live The KingThe King is Dead, Long Live The KingThe King is Dead, Long Live The King 


### Question 8

In [18]:
def ch(n):
    if n == 1:
        print('one')
    elif n == 2:
        print('two')
    else:
        print('not 1 or 2')

def ran(n):
    for i in range(n):
        print(i)
        
print('enter choice')
ch(int(input()))

print('enter range :')
ran(int(input()))



enter choice


 1


one
enter range :


 3


0
1
2


### Question 9

In [22]:
str = "The King is Dead, Long Live The King"
print(str)
print(str[0])
print(str[2:5])
print(str[2:])
print(str.split(' '))

The King is Dead, Long Live The King
T
e K
e King is Dead, Long Live The King
['The', 'King', 'is', 'Dead,', 'Long', 'Live', 'The', 'King']


### Question 10

In [24]:
arr = list([1,4,5,8])
print(arr[0:2])

[1, 4]


## Second Half

10.	An array can be created from a list:  Create an array from a list comprising of numbers 1,4,5,8 (treat them as floats).Slice the above array to display first and second elements
11.	Arrays can be multidimensional. Create a two-dimensional array of (1,2,3) and (4,5,6).
12.	Array slicing works with multiple dimensions in the same way as usual, applying each slice specification as a filter to a specified dimension. Consider two-dimensional array of (1,2,3) and (4,5,6).
- Slice and display the 2nd row.
- Write code to display as array([2., 5.]) 
- Find the length of the array.
13.	Arrays can be reshaped using tuples that specify new dimensions. Turn a ten-element one-dimensional array into a two-dimensional one whose first axis has five elements and whose second axis has two elements. Obtain the transpose of the array
14.	Create an array from a list of 1,2 and 3.
15.	Fill an array [1,2,3] with a single value [9,9,9]. 
16.	Sum the elements of array [2,4,5].
17.	Give the products of array [77,74,75]
18.	Given an array [2,1,9,1,2,22,1,1,4,55,6,2,56]. Find mean, variance, max, min, argmin, median, argmax and standard deviation.
19.	Extract unique elements from an array: [1, 1, 4, 5, 5, 5, 7] and sort it.
20.	Find dot product of two arrays [1, 2, 3]and [0, 1, 1]. 
21.	Find the eigenvalues and eigenvectors of matrix A.
22.	Given an array with [11, 22, 11, 31], [25, 33, 31, 28]]. Treat as floats. Find the correlation coefficients.

### Question 11

In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


### Question 12

In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr = arr.astype('float64')
print(arr[0:2,1])

print(arr.size)
print(arr.shape)

[2. 5.]
6
(2, 3)


### Question 13

In [9]:
arr=[1,2,3,4,5,6,7,8,9,10]
arr2=np.array(arr)

newarr = arr2.reshape(2, 5)
print(newarr)
newarr1 = arr2.reshape(5, 2)
print(newarr1)

print("Transpose : ")
print(newarr.transpose())
print(newarr1.transpose())

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
Transpose : 
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]


### Question 14

In [11]:
li1 = [1,2,3]
arr=np.array(li1)
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


### Question 15

In [12]:
li1 = [1,2,3]
arr=np.array(li1)

arr[0]=9
arr[1]=9
arr[2]=9
print(arr)
print(type(arr))

[9 9 9]
<class 'numpy.ndarray'>


### Question 16

In [25]:
arr = [2,4,5]
print(sum(arr))

11


### Question 17


In [26]:
arr = [77,74,75]
prod = 1
for i in arr:
    prod*=i
print(prod)

427350


### Question 18

In [37]:
arr = np.array([2,1,9,1,2,22,1,1,4,55,6,2,56])
# mean, variance, max, min, argmin, median, argmax and standard deviation
print('Mean : ', arr.mean())
print('var : ', arr.var())
print('max : ', arr.max())
print('min ; ', arr.min())
print('argmin : ', arr.argmin())
print('median : ', np.median(arr))
print('argmax : ', arr.argmax())
print('sd : ', np.std(arr))

Mean :  12.461538461538462
var :  367.32544378698225
max :  56
min ;  1
argmin :  1
median :  2.0
argmax :  12
sd :  19.165736192147232


### Question 19

In [38]:
li = [1, 1, 4, 5, 5, 5, 7]
uniq = list(set(li))
uniq.sort()
print(uniq)

[1, 4, 5, 7]


### Question 20

In [39]:
li1 = [1, 2, 3]
li2 = [0, 1, 1]

prod = 0

for i in range(len(li1)):
    temp = li1[i]*li2[i]
    prod+=temp
    
print(prod)

5


### Question 21

In [41]:
matA = [[1, -12], [1, -5]]

eigenVal, eigenVect = np.linalg.eig(matA)

print('eigen values : ', eigenVal)
print('eigen vectors : ', eigenVect)

eigen values :  [-2.+1.73205081j -2.-1.73205081j]
eigen vectors :  [[0.96076892+0.j         0.96076892-0.j        ]
 [0.24019223-0.13867505j 0.24019223+0.13867505j]]


### Question 22

In [58]:
li1 = np.array([11, 22, 11, 31])
li2 = np.array([25, 33, 31, 28])

ret = np.corrcoef(li1,li2)
print(ret)

[[1.         0.15997968]
 [0.15997968 1.        ]]
